name: Linux, gcc, EDK2

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

env:
  COMPILER: GCC5
  GCC5_ARM_PREFIX: arm-linux-gnueabi-
  GCC5_AARCH64_PREFIX: aarch64-linux-gnu-
  GCC5_RISCV64_PREFIX: riscv64-linux-gnu-
  GCC5_LOONGARCH64_PREFIX: loongarch64-unknown-linux-gnu-
  FULL_SHELL_GUID: EA4BB293-2D7F-4456-A681-1F22F42CD0BC
  # Shell versions:
  #  2.2 added on 2017.03.31
  #  2.1 added on 2014.08.05
  #  2.0 added on 2009.05.11
  EDK2_SHELL_VERSION_HEADER: edk2/MdePkg/Include/Protocol/Shell.h
  # Was edk2/ShellPkg/Include/Protocol/EfiShell.h prior to 2016.10.18 
  # enum ShellVersion added on 2009.05.11

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TYPES: [ DEBUG, RELEASE ]
        ARCHS: [ X64, IA32, AARCH64, ARM, RISCV64, LOONGARCH64 ]


    steps:
    - name: Checkout repository and submodules
      # Must happen first, else the LoongArch toolchain gets deleted (even with clean: false)
      uses: actions/checkout@v4.2.2
      with:
        # Need fetch-depth: 0 to obtain the EDK2 stable tag
        fetch-depth: 0
        submodules: recursive

    - name: Install toolchains
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install gcc-12-multilib gcc-12-aarch64-linux-gnu gcc-12-arm-linux-gnueabi gcc-12-riscv64-linux-gnu nasm genisoimage uuid-dev
        sudo ln -s /usr/bin/aarch64-linux-gnu-gcc-12 /usr/bin/aarch64-linux-gnu-gcc
        sudo ln -s /usr/bin/aarch64-linux-gnu-gcc-ar-12 /usr/bin/aarch64-linux-gnu-gcc-ar
        sudo ln -s /usr/bin/arm-linux-gnueabi-gcc-12 /usr/bin/arm-linux-gnueabi-gcc
        sudo ln -s /usr/bin/arm-linux-gnueabi-gcc-ar-12 /usr/bin/arm-linux-gnueabi-gcc-ar
        sudo ln -s /usr/bin/riscv64-linux-gnu-gcc-12 /usr/bin/riscv64-linux-gnu-gcc
        sudo ln -s /usr/bin/riscv64-linux-gnu-gcc-ar-12 /usr/bin/riscv64-linux-gnu-gcc-ar
        curl -L -O https://github.com/loongson/build-tools/releases/download/2024.11.01/x86_64-cross-tools-loongarch64-binutils_2.43.1-gcc_14.2.0-glibc_2.40.tar.xz
        tar -xJf x86_64-cross-tools-loongarch64-binutils_2.43.1-gcc_14.2.0-glibc_2.40.tar.xz
        echo "$PWD/cross-tools/bin" >> "$GITHUB_PATH"

    - name: Set version
      id: set_version
      run: |
        SHELL_MAJOR_VERSION=$(awk '/SHELL_MAJOR_VERSION/{sub("\r", "", $NF); sub(",", "", $NF); print $NF}' ${{ env.EDK2_SHELL_VERSION_HEADER }})
        SHELL_MINOR_VERSION=$(awk '/SHELL_MINOR_VERSION/{sub("\r", "", $NF); print $NF}' ${{ env.EDK2_SHELL_VERSION_HEADER }})
        # NB: The following only works if the shell is bash
        echo "shell_version=${SHELL_MAJOR_VERSION}.${SHELL_MINOR_VERSION}" >> $GITHUB_OUTPUT
        echo "shell_release=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
        echo "edk2_tag=$(git --git-dir edk2/.git describe --tags)" >> $GITHUB_OUTPUT
        echo "build_date=$(date '+%Y.%m.%d')" >> $GITHUB_OUTPUT

    - name: Set up EDK2
      run: make -C edk2/BaseTools

    - name: Build UEFI binaries
      run: |
        cd edk2
        source edksetup.sh
        build -a ${{ matrix.ARCHS }} -b ${{ matrix.BUILD_TYPES }} -t ${{ env.COMPILER }} -p ShellPkg/ShellPkg.dsc --pcd gEfiShellPkgTokenSpaceGuid.PcdShellScreenLogCount=8 --pcd gEfiShellPkgTokenSpaceGuid.PcdShellSupplier=L"${{ steps.set_version.outputs.edk2_tag }} (https://github.com/pbatard/UEFI-Shell)"


    - name: Create individual Shell binaries
      run: |
        cp edk2/Build/Shell/RELEASE_${{ env.COMPILER }}/${{ matrix.ARCHS }}/Shell_${{ env.FULL_SHELL_GUID }}.efi ./shell${ARCH,,}.efi
        if [ -f ./shellaarch64.efi ]; then
          mv ./shellaarch64.efi ./shellaa64.efi
        fi

    - name: Download the latest Mosby release
      uses: robinraju/release-downloader@v1.12
      with:
        repository: pbatard/Mosby
        latest: true
        fileName: Mosby*.zip

    - name: Extract the Mosby content
      run: |
          mkdir ${{ matrix.BUILD_TYPES }}
          7z x Mosby*.zip -o${{ matrix.BUILD_TYPES }}
          mv ${{ matrix.BUILD_TYPES }}/README.md ${{ matrix.BUILD_TYPES }}/Mosby.txt
          sed -i '1,5d' ${{ matrix.BUILD_TYPES }}/Mosby.txt

    - name: Create ISO filesystem structure
      run: |
          mkdir -p ${{ matrix.BUILD_TYPES }}/efi/boot
          mv edk2/Build/Shell/${BUILD_TYPE}_${{ env.COMPILER }}/${{ matrix.ARCHS }}/Shell_${{ env.FULL_SHELL_GUID }}.efi ${{ matrix.BUILD_TYPES }}/efi/boot/boot${ARCH,,}.efi

          if [ -f ${{ matrix.BUILD_TYPES }}/efi/boot/bootaarch64.efi ]; then
            mv ${{ matrix.BUILD_TYPES }}/efi/boot/bootaarch64.efi ${{ matrix.BUILD_TYPES }}/efi/boot/bootaa64.efi
          fi
          printf "*** UEFI Shell v%s, release %s%s ***\n\n" ${{ steps.set_version.outputs.shell_version }} ${{ steps.set_version.outputs.shell_release }} "$( [ ${{ matrix.BUILD_TYPES }} == DEBUG ] && echo ' (DEBUG BUILD)')" > ${{ matrix.BUILD_TYPES }}/README.txt
          printf "This bootable image contains builds of the official UEFI Shell, as provided by\n" >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "the Open Source 'EDK2' project (https://github.com/tianocore/edk2).\n\n" >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "More specifically, this release, which we call '%s', was produced using the\n" ${{ steps.set_version.outputs.shell_release }} >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "'%s' version of the EDK2 source available at:\n" ${{ steps.set_version.outputs.edk2_tag }} >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "https://github.com/tianocore/edk2/releases/tag/%s\n\n" ${{ steps.set_version.outputs.edk2_tag }} >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "This image supports the following UEFI platform architectures:\n" >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "* %s\n" ${{ matrix.ARCHS }} >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "\nReleases of UEFI Shell now also include Mosby (https://github.com/pbatard/Mosby)\n" >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "to help you update your Secure Boot variables as well as generate and install\n" >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "your own Secure Boot signing key. Just type 'Mosby' to run it.\n" >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "\nFor more information on how this release was produced, you are invited to\n" >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "visit our official project page at https://github.com/pbatard/UEFI-Shell,\n" >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "where you can also validate that all of the binaries contained in this image\n" >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "were built from the unmodified EDK2 source, through an automated build process\n" >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "that guarantees that no malicious code can have been injected.\n" >> ${{ matrix.BUILD_TYPES }}/README.txt
          printf "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" > Version.xml
          printf "<release>\n" >> Version.xml
          printf "  <name>%s (%s)</name>\n" ${{ steps.set_version.outputs.shell_release }} ${{ steps.set_version.outputs.edk2_tag }} >> Version.xml
          printf "  <shell_version>%s</shell_version>\n" ${{ steps.set_version.outputs.shell_version }} >> Version.xml
          printf "  <build_date>%s</build_date>\n" ${{ steps.set_version.outputs.build_date }} >> Version.xml
          printf "  <supported_archs>\n" >> Version.xml
          printf "    <arch>%s</arch>\n" ${{ matrix.ARCHS }} >> Version.xml
          printf "  </supported_archs>\n" >> Version.xml
          printf "</release>\n" >> Version.xml

    - name: Generate ISO images
      run: |
          genisoimage -v -V "UEFI SHELL ${{ steps.set_version.outputs.shell_version }} ${{ steps.set_version.outputs.shell_release }} (${{ matrix.BUILD_TYPES }})" -JR -o "UEFI-Shell-${{ steps.set_version.outputs.shell_version }}-${{ steps.set_version.outputs.shell_release }}-${{ matrix.BUILD_TYPES }}.iso" ${{ matrix.BUILD_TYPES }}

    - name: Display SHA-256
      run: |
        sha256sum ${{ matrix.BUILD_TYPES }}/efi/boot/*.efi
        sha256sum *.iso
        sha256sum *.efi

    - name: Upload ISO artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ISOs
        path: ./*.iso

    - name: Create release blurb
      run: |
        printf "**UEFI Shell v%s, release %s**\n\n" ${{ steps.set_version.outputs.shell_version }} ${{ steps.set_version.outputs.shell_release }} > body.txt
        printf "Built from [%s](https://github.com/tianocore/edk2/releases/tag/%s) and supporting:\n" ${{ steps.set_version.outputs.edk2_tag }} ${{ steps.set_version.outputs.edk2_tag }} >> body.txt
        printf "* \`%s\`\n" ${{ matrix.ARCHS }} >> body.txt
        printf "\nsha256sums:\n" >> body.txt
        printf "\`\`\`\n" >> body.txt
        sha256sum ./*.efi >> body.txt
        sha256sum ./*.iso >> body.txt
        printf "\`\`\`\n" >> body.txt

    - name: Create release
      uses: softprops/action-gh-release@v2.3.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body_path: ./body.txt
        files: |
          ./*.iso
          ./*.efi
          ./Version.xml
